dependencies:
  - aave/aave-v3-core@1.17.2
compiler:
  solc:
    remappings:
      - '@aave=aave/aave-v3-core@1.17.2'
dotenv: .env

networks:
  default: mainnet-fork  
  sepolia:
    weth_token: "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"  
    pool_addresses_provider: "0x0496275d34753A48320CA58103d5220d394FF77F" 
  mainnet-fork: 
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" 
    pool_addresses_provider: "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e" 

wallets:
  from_key: ${PRIVATE_KEY}


